language: python
notifications:
  email:
    on_success: never
    on_failure: change
python:
  - "2.7"
os:
  - windows
before_install:
  - pip install wikitools
script: python master.py
username:
  secure: aUJGOI5vFWil3bvMq/HriaH5DhAENHtfw+1OpSi28cvwS3H7kkQUqRMVE5UoMPmeKYEWPvSI90OrunK2WNXZWcnSg4RfteiHkgZ1ZkLGTWj3BG49dHZPc2Wj0g3LHyjomvL/SB8OixwSSDuSH+KV1AU93alTEnjUM4hPj2ACs3q0/BiyHmQnRVvLTCvKfJYrWUfv72zCbmOIYlgGZ/7f7qfNhHVMhpPDkkz1IEwMlxHAJ/3kNqV29R4apoPHJdcSicHvlzdGP0h95Y7OS1Uup0j6aVUhOmGleXlzqq6ZH/HgUQMdKKLxLr247yK8PTncDZUQLyDxh+2iB9mq3i6Zn7UfrOeOCzG2WjrtmV47f6oLCFhdMREwpsN2RO+ECW6IyMrK1GaumKbkcc1wAaFa7gXN7PxFXP2Yvs2TVm7DoVvWZAC9oFZRMK0whwrT/S3gxkW6A019cYt0eY7pCJFtFzp5nCULTT+TgraUThyBv/4trqodfjzh6uFhHH1pemFN9n1owtZlrxxtLHmywg55eiQTEdxTMEALnNTea2y6xe/8WxSUSEeUAhgTpkm6zy+sEiYSQq9eiWnsoKrVakiQevOb6HHitr2sFh2d1oPyaIlhfr2yDZB5ZpEzbul0O2k3Dos5EE2EI/oQJwx5hpAR9IwQWs8HFO3iRAIlJvOEJAU=
password:
  secure: SH0iaOx91I47xUN3tEWjs/W34OOe5yL2qBP1tMU24S+csEzY0r2dw/2s6Wyn3Ik8Pr88UGP+odKcPAZa/4GT3ojA9IFpFc7pR0JQRvVd6GWXcnsd1yY2hDC1xRnCX/Rp65OIbJTOTqZaaT7bKRGUkfYp3X+pVBsKNoyZyYKrC/wgxp4k8GQymd3X7sZCTUto2ePQ3jGjVRGGLJdfYBrBWoON4W8BV3rWdWk5k/DDXwUQZkucBS15GqkxEqsDAD8DS6l7YKIFagCq79tAQm62IpjiYZlBo6IMopSRt/38deLGBoHG0JhIv1pYIsfGlX1J316G2zv7lm1PJUP3j2Y7PZLfo23MlTxx0vpFONmNodxWo+CJA9Zt0yIP00OifES8zp9Bs7Qr5ssI36b1LAYcyUnQeNcnlSY3fgQrET69HXZBrsS2GSU4H0MrFaAaW9hCP3QgyXd4H3bWkM5q+j73bbz2tE/hsNYQjS4TdlNmP4U9QsQF8ee7ao+UFZfCcwXRC9NMEIyZ4rwyZ1GPQ9P4ix5os64JNZPM0Xy0q7lTOW7l66/GuL1lXZpkebFbQZSBz+uC35It6K07HlZzh1uhGmVl8V9qw6PVy6kl+Y5jr0VwoySBHWGbknqpdOdpbkSGSRcj99wBQ4OCevEGJuhKKxYf1m6vmeNlnhswLEhjArI=
