language: python
notifications:
  email:
    on_success: never
    on_failure: change
python:
  - '2.7'
os:
  - windows
script: python Master.py $WIKI_PASSWORD
environ:
  secure: nBoRvjBBCGcWPsmeXocuzaalKTefG9G12g4D64m00Mhb52EfaoZIMg8SfHZhHA6aqDrl5z2pQ21qSBHBVhb7MFTFAs1jXeQtG92phkP9rfxBRMPfj/1lHYgU9GaTMkX1dIg1nn7pPj2vKdzZThFleVm7FnVE1/5gkkoR18Cl2SUJ91m6ASQm1NLCj6iJWkkENWcP6VpuUt8Sz+SpcZHTbMwAj0wwLxCBFR3B9etXMn2knV3k8kqit/LBdqHtrWS/CjZZjQTsu5S4UhK+v5gBicomNCb0V262voCIqI+5HmB/ifZDnQyet9X8MqdoBL2nxgru0uZw1eD+DZbMw4a4kbGIhoju4X8cfMtYC/Mg5q/E62vedMbW9klG634J5Pxsq2XDBwlBkrfAeVA33VdNKxr26SruPXmAhKS32wz2/5ULP6R8J/P0Rtpl0eBcwF7i7TmCm9lE37N4xkx9PoYMkIfpWC0146zGXnPk/1K59w+pmMXKBfn8cfw4kCCw6Lvf8iihjuBvpVk/fLB2VAWwIK506MdGO1Ad4SWvrArWbd7NZe7S/p+k0f/D5pS4V7hRfXR1xWst2z8DKcmKOSNRB3O4aEGq38ALDEcc/hTJ50FWkl6LQ/i+OsVHzlvdrfiNnEEVzZwjGO6WyzPW7XjH/VTuGDugU3eFi3DQyXVNR/U=
